# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
                ('comment_body', models.TextField()),
            ],
        ),
    ]
